routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Customer\CustomerController;
use App\Http\Controllers\Customer\CustomerOrderController;
use App\Http\Controllers\DeliveryMan\DeliveryManController;
use App\Http\Controllers\Auth\LoginController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes();

// Route::post('/main/checklogin', [LoginController::class,'checklogin']);
// Route::get('/redirect', [LoginController::class,'redirectTo']);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/change/password', [App\Http\Controllers\Auth\LoginController::class, 'changePasswordUI'])->name('changePasswordUI');
Route::post('/change-password', [App\Http\Controllers\Auth\LoginController::class, 'changePasswordConfirm'])->name('changePasswordConfirm');

/// Admin
Route::get('/adminDashboard', [AdminController::class,'index'])->name('adminDashboard')->middleware('admin');
Route::get('/admin-list', [AdminController::class,'list'])->name('admin.list')->middleware('admin');
Route::post('/admin/add/', [AdminController::class,'add'])->name('admin.add')->middleware('admin');
Route::post('/admin/updateData/', [AdminController::class,'updateData'])->name('admin.updateData')->middleware('admin'); 
Route::delete('/deleteAdmin/{id}', [AdminController::class,'deleteAdmin'])->name('admin.deleteAdmin')->middleware('admin');
//Route::get('/details/{id}', [AdminController::class,'details'])->name('admin.details')->middleware('admin');
Route::get('/admin/order-list/', [CustomerOrderController::class,'getDeliveryOrderForAdmin'])->name('admin.getDeliveryOrderForAdmin')->middleware('admin');
Route::post('/admin/order-reject/', [CustomerOrderController::class,'orderReject'])->name('order.order-reject')->middleware('admin');
Route::post('/admin/assign-delivery-man/', [CustomerOrderController::class,'assignDeliveryMan'])->name('order.order-assign-delivery-man')->middleware('admin');
Route::get('/admin/order-history/', [CustomerOrderController::class,'adminOrderHistory'])->name('admin.adminOrderHistory')->middleware('admin');

/// Customer
Route::get('/customerDashboard', [CustomerController::class,'index'])->name('customerDashboard')->middleware('customer');
Route::get('/customer-list', [CustomerController::class,'list'])->name('customer.list')->middleware('admin');
Route::get('/details-customer/{id}', [CustomerController::class,'detailsCustomer'])->name('customer.detailsCustomer')->middleware('admin');

Route::resource('customer-order',CustomerOrderController::class)->middleware('customer');;
Route::get('/customer/new-order', [CustomerOrderController::class,'newOrderRequest'])->name('customer-order.newOrderRequest')->middleware('customer');
Route::get('/customer/running-order/', [CustomerOrderController::class,'runnngOrder'])->name('customer-order.runnngOrder')->middleware('customer');
Route::get('/customer/order-history/', [CustomerOrderController::class,'orderHistory'])->name('customer-order.orderHistory')->middleware('customer');

/// Delivery Man
Route::get('/deliveryManDashboard', [DeliveryManController::class,'index'])->name('deliveryManDashboard')->middleware('deliveryMan');
Route::get('/delivery-man-list', [DeliveryManController::class,'list'])->name('delivery-man.list')->middleware('admin');
Route::post('/delivery-man/add/', [DeliveryManController::class,'add'])->name('delivery-man.add')->middleware('admin');
Route::post('/delivery-man/updateData/', [DeliveryManController::class,'updateData'])->name('delivery-man.updateData')->middleware('admin'); 
Route::delete('/deleteDeliveryMan/{id}', [DeliveryManController::class,'delete'])->name('delivery-man.delete')->middleware('admin');
Route::get('/detailsDeliveryMan/{id}', [DeliveryManController::class,'details'])->name('delivery-man.details')->middleware('admin');
Route::get('/delivery-man/assign-order-list/', [CustomerOrderController::class,'assignOrderList'])->name('order.assign-order-list')->middleware('deliveryMan');
Route::get('/delivery-man/completed/', [CustomerOrderController::class,'deliveryManCompleted'])->name('order.delivery-man-completed')->middleware('deliveryMan');

Route::get('/order-details/{id}', [CustomerOrderController::class,'orderDetails'])->name('order.order-details')->middleware('deliveryMan');  // 'deliveryMan','admin', customer -- here Data :p 
Route::get('/order-details-admin/{id}', [CustomerOrderController::class,'orderDetails'])->name('order.order-details-admin')->middleware('admin');  // 'deliveryMan','admin', customer
Route::get('/order-details-customer/{id}', [CustomerOrderController::class,'orderDetails'])->name('order.order-details-customer')->middleware('customer');  // 'deliveryMan','admin', customer

Route::post('/assign-order-received', [CustomerOrderController::class,'assignOrderReceived'])->name('order.assign-order-received')->middleware('deliveryMan');
Route::post('/assign-order-add-location', [CustomerOrderController::class,'assignOrderAddLocation'])->name('order.assign-order-add-location')->middleware('deliveryMan');
Route::post('/assign-order-complete', [CustomerOrderController::class,'assignOrderComplete'])->name('order.assign-order-complete')->middleware('deliveryMan');
Route::get('/map/{id}', [CustomerOrderController::class,'mapView'])->name('order.map'); //->middleware('deliveryMan');

app/Http/Controllers/Customer/CustomerController.php
<?php

namespace App\Http\Controllers\Customer;

use App\Http\Controllers\Controller;
use App\Http\Controllers\CommonController;
use App\Models\Orders;
use App\Models\User;
use Illuminate\Http\Request;
use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use \PDF;
use Validator;
use App\Models\OrderActionStatus;
use CreateOrderActionStatus;

class CustomerController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->common_class_obj = new CommonController();
    }

    //
    public function index()
    {
        $totalCompletedOrders = Orders::where([['customer_id' , '=',Auth::user()->id],['order_status', '=', 5], ['active_status', '=', 1]])->count();
         
        $totalRunningOrders = Orders::where([['customer_id' , '=',Auth::user()->id],['active_status', '=', 1]])->whereIn('order_status', [1,2,3])->count();
        
        $totalPendingOrders = Orders::where([['customer_id' , '=',Auth::user()->id],['order_status', '=', 0], ['active_status', '=', 1]])->count();

        $runningOrderList = Orders::where([
            ['customer_id', '=', Auth::user()->id],
            ['order_status', '!=', 5],
            ['active_status', "!=", 0]
        ])->orderBy('id', 'DESC')->limit(5)->get();
        return view('customer.customerDashboard',compact('totalCompletedOrders','totalRunningOrders','totalPendingOrders','runningOrderList'));
    }

    public function list()
    {
        
        $customerList = User::where([['role_id', '=', 3]])->get();
        
        return view('customer.list',compact('customerList'));
    }

    public function detailsCustomer($id)
    {
        
        $customer = User::findorFail($id);
        $runningOrderList = Orders::where([['customer_id', '=', $id]])->orderBy('id', 'DESC')->get();

        $complete_order = 0;
        $running_order = 0;
        $cancel_order = 0;

        for ($i=0; $i < count($runningOrderList); $i++) { 
            if ($runningOrderList[$i]->order_status == 5) $complete_order++;
            else if ($runningOrderList[$i]->order_status == -1) $cancel_order++;
            else if ($runningOrderList[$i]->order_status > 0  && $runningOrderList[$i]->order_status < 5)  $running_order++;
        }

        return view('customer.details', compact('customer', 'id', 'runningOrderList', 'cancel_order', 'complete_order', 'running_order' ));
    }

    
}

resources/views/customer/customerDashboard.blade.php
@extends('layouts.app')

@section('content')
    <!-- Main Content -->
    <div class="main-content">
        <section class="section">
            <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-12">
                    @if ($errors->any())
                        <div class="col-sm-12">
                            <div class="alert  alert-warning alert-dismissible fade show" role="alert">
                                @foreach ($errors->all() as $error)
                                    <span>
                                        <p>{{ $error }}</p>
                                    </span>
                                @endforeach
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        </div>
                    @endif

                    @include('flash-message')
                    <div class="card card-statistic-2">
                        <div class="card-icon shadow-primary bg-primary">
                            <i class="fas fa-archive"></i>
                        </div>
                        <div class="card-wrap">
                            <div class="card-header">
                                <h4>Total Completed</h4>
                            </div>
                            <div class="card-body">
                                {{ $totalCompletedOrders }}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-12">
                    <div class="card card-statistic-2">
                        <div class="card-icon shadow-primary bg-primary">
                            <i class="fas fa-dollar-sign"></i>
                        </div>
                        <div class="card-wrap">
                            <div class="card-header">
                                <h4>Total Running</h4>
                            </div>
                            <div class="card-body">
                                {{ $totalRunningOrders }}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-12">
                    <div class="card card-statistic-2">
                        <div class="card-icon shadow-primary bg-primary">
                            <i class="fas fa-shopping-bag"></i>
                        </div>
                        <div class="card-wrap">
                            <div class="card-header">
                                <h4>Pending Orders</h4>
                            </div>
                            <div class="card-body">
                                {{ $totalPendingOrders }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <h4>Running Orders</h4>
                            <div class="card-header-action">
                                <a href="{{ route('customer-order.runnngOrder') }}" class="btn btn-danger">View More <i
                                        class="fas fa-chevron-right"></i></a>
                            </div>
                        </div>
                        <div class="card-body p-0">
                            <div class="table-responsive table-invoice">
                                <table class="table table-striped">
                                    <tr>
                                        <th>#</th>
                                        <th>Order Date</th>
                                        <th>Delivered To</th>
                                        <th>Contact Number</th>
                                        <th>Status</th>
                                        <th>Action</th>
                                    </tr>
                                    <tbody>
                                        @foreach ($runningOrderList as $key => $order)
                                            <tr>
                                                <td>{{ $key + 1 }}</td>
                                                <td>{{ \Carbon\Carbon::parse($order->created_at)->format('d/m/Y') }}</td>
                                                <td>{{ $order->delivered_to }}</td>
                                                <td>{{ $order->contact_number }}</td>
                                                <td>
                                                    @if ($order->order_status == -1)
                                                        Reject
                                                    @elseif($order->order_status == 0)
                                                        Pending
                                                    @elseif($order->order_status == 1)
                                                        Accepted
                                                    @elseif($order->order_status == 2)
                                                        Received
                                                    @elseif($order->order_status == 3)
                                                        On the way
                                                    @elseif($order->order_status == 5)
                                                        Delivered
                                                    @endif
                                                </td>
                                                {{-- <td>
                          <div class="badge badge-warning">Unpaid</div>
                      </td> --}}
                                                <td>
                                                    <a href="{{ route('order.order-details-customer', $order->id) }}"
                                                        class="btn btn-primary"> View Details </a>

                                                    <a type="button"
                                                        href="{{ route('customer-order.edit', $order->id) }}"
                                                        class="btn btn-warning">
                                                        Edit
                                                    </a>
                                                </td>
                                            </tr>

                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/customer/newOrderRequest.blade.php
@extends('layouts.app')
@section('title', 'Customer')
@push('css')


@endpush

@section('content')

<!-- Main Content -->
<div class="main-content">
    <section class="section">
        <div class="col-12 section-header">
            <div class="col-6">
                <h1>New Order</h1>
            </div>
            <div class="col-6 d-flex flex-row-reverse">

            </div>
        </div>

        @if ($errors->any())
        <div class="col-sm-12">
            <div class="alert  alert-warning alert-dismissible fade show" role="alert">
                @foreach ($errors->all() as $error)
                <span>
                    <p>{{ $error }}</p>
                </span>
                @endforeach
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        </div>
        @endif

        @include('flash-message')

        <div class="section-body">
            <div class="col-12">
                <div class="card">
                    <form method="POST" action="{{ route('customer-order.store') }}" enctype="multipart/form-data">
                        {{ csrf_field() }}
                        <div class="card">
                            <div class="card-body">
                                <div class="form-group">
                                    <label>Product Category</label>
                                    <select class="form-control " name="product_category">
                                        <option value="" selected="selected">Select A Product Category</option>
                                        <option value="Frozen Products">Frozen Products</option>
                                        <option value="Foods & Drinking Products">Foods & Drinking Products</option>
                                        <option value="Furniture, Electronic Goods">Furniture, Electronic Goods</option>

                                    </select>
                                </div>
                                <div class="form-group">
                                    <label>Product Weight</label><code>(in KG)</code>
                                    <input type="number" class="form-control" name="product_weight">
                                </div>
                                <div class="form-group">
                                    <label>Delivered To</label>
                                    <input type="text" class="form-control" name="delivered_to">
                                </div>
                                <div class="form-group">
                                    <label>Pickup Adress</label>
                                    <textarea type="text" class="form-control" placeholder="Enter Full Address" name="pickup_address"></textarea>
                                </div>
                                <div class="form-group">
                                    <label>Destination Adress</label>
                                    <textarea type="text" class="form-control" placeholder="Enter Full Address" name="destination_address"></textarea>
                                </div>
                                <div class="form-group">
                                    <label>Phone Number</label>
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                            <div class="input-group-text">
                                                <i class="fas fa-phone"></i>
                                            </div>
                                        </div>
                                        <input type="number" class="form-control phone-number" name="contact_number">
                                    </div>
                                </div>

                                <div class="form-group text-right">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                </div>
                            </div>

                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>


</div>

@endsection

@section('extra-js')


<script>

</script>
@endsection

resources/views/customer/runningOrderList.blade.php
@extends('layouts.app')
@section('title', 'Customer')
@push('css')


@endpush

@section('content')

    <!-- Main Content -->
    <div class="main-content">
        <section class="section">
            <div class="col-12 section-header">
                <div class="col-6">
                    <h1>Running Orders</h1>
                </div>

            </div>

            @if ($errors->any())
                <div class="col-sm-12">
                    <div class="alert  alert-warning alert-dismissible fade show" role="alert">
                        @foreach ($errors->all() as $error)
                            <span>
                                <p>{{ $error }}</p>
                            </span>
                        @endforeach
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                </div>
            @endif

            @include('flash-message')

            <div class="section-body">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body p-0">
                            <div class="table-responsive">
                                <table id="example" class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Order Date</th>
                                            <th>Delivered To</th>
                                            <th>Contact Number</th>
                                            <th>Status</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach ($runningOrderList as $key => $order)
                                            <tr>
                                                <td>{{ $key + 1 }}</td>
                                                <td>{{ \Carbon\Carbon::parse($order->created_at)->format('d/m/Y') }}</td>
                                                <td>{{ $order->delivered_to }}</td>
                                                <td>{{ $order->contact_number }}</td>
                                                <td>
                                                    @if ($order->order_status == -1)
                                                        Reject
                                                    @elseif($order->order_status == 0)
                                                        Pending
                                                    @elseif($order->order_status == 1)
                                                        Accepted
                                                    @elseif($order->order_status == 2)
                                                        Received
                                                    @elseif($order->order_status == 3)
                                                        On the way
                                                    @elseif($order->order_status == 5)
                                                        Delivered
                                                    @endif
                                                </td>
                                                {{-- <td>
                                                <div class="badge badge-warning">Unpaid</div>
                                            </td> --}}
                                                <td>
                                                    <a href="{{ route('order.order-details-customer', $order->id) }}"
                                                        class="btn btn-primary"> View Details </a>

                                                    <a type="button" href="{{ route('customer-order.edit', $order->id) }}"
                                                        class="btn btn-warning">
                                                        Edit
                                                    </a>
                                                </td>
                                            </tr>

                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

    </div>


@endsection

@section('extra-js')

@endsection

resources/views/customer/updateOrder.blade.php
@extends('layouts.app')
@section('title', 'Customer')
@push('css')


@endpush

@section('content')

    <!-- Main Content -->
    <div class="main-content">
        <section class="section">
            <div class="col-12 section-header">
                <div class="col-6">
                    <h1>Update Order</h1>
                </div>
                <div class="col-6 d-flex flex-row-reverse">

                </div>
            </div>

            @if ($errors->any())
                <div class="col-sm-12">
                    <div class="alert  alert-warning alert-dismissible fade show" role="alert">
                        @foreach ($errors->all() as $error)
                            <span>
                                <p>{{ $error }}</p>
                            </span>
                        @endforeach
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                </div>
            @endif

            @include('flash-message')

            <div class="section-body">
                <div class="col-12">
                    <div class="card">
                        
                        <form method="POST" action="{{ route('customer-order.update', $id) }}" enctype="multipart/form-data">
                            {{ method_field('PATCH') }}
                                {{ csrf_field() }}
                            <div class="card">
                                <div class="card-body">
                                    <div class="form-group">
                                        <label>Product Category</label>
                                        <select class="form-control " name="product_category">
                                            <option value="Frozen Products" <?php if ($order->product_category == "Frozen Products") {
                                                echo 'selected';
                                            } ?> >Frozen Products</option>
                                            <option value="Foods & Drinking Products" <?php if ($order->product_category == "Foods & Drinking Products") {
                                                echo 'selected';
                                            } ?> >Foods & Drinking Products</option>
                                            <option value="Furniture, Electronic Goods" <?php if ($order->product_category == "Furniture, Electronic Goods") {
                                                echo 'selected';
                                            } ?> >Furniture, Electronic Goods</option>
                                            
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        <label>Product Weight</label><code>(in KG)</code>
                                        <input type="number" class="form-control" name="product_weight" value="{{ $order->product_weight }}">
                                    </div>
                                    <div class="form-group">
                                        <label>Delivered To</label>
                                        <input type="text" class="form-control" name="delivered_to" value="{{ $order->delivered_to }}">
                                    </div>
                                    <div class="form-group">
                                        <label>Pickup Adress</label>
                                        <textarea type="text" class="form-control" placeholder="Enter Full Address"
                                            name="pickup_address" value="">{{ $order->pickup_address }}</textarea>
                                    </div>
                                    <div class="form-group">
                                        <label>Destination Adress</label>
                                        <textarea type="text" class="form-control" placeholder="Enter Full Address"
                                            name="destination_address" value="">{{ $order->destination_address }}</textarea>
                                    </div>
                                    <div class="form-group">
                                        <label>Phone Number</label>
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <div class="input-group-text">
                                                    <i class="fas fa-phone"></i>
                                                </div>
                                            </div>
                                            <input type="number" class="form-control phone-number" name="contact_number" value="{{ $order->contact_number }}">
                                        </div>
                                    </div>
                                    <input type="hidden" name="id" id="id" value="{{ $order->id }}"
                                    class="form-control form-control-lg" />

                                    <div class="form-group text-right">
                                        <button type="submit" class="btn btn-primary">Update</button>
                                    </div>
                                </div>

                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>


    </div>

@endsection

@section('extra-js')


    <script>

    </script>
@endsection